<?php
/**
 * 08-inject-fixed.php -- Bahari Segar Design Fix
 * Generated by 08-design-fix.py
 * Surface light: #E7E9E1 (fixed from #F3EFE4)
 */

define('WA',  'https://wa.me/6281234567890');
define('SL',  '#E7E9E1');  // surface-light: abu-hijau es/beton
define('H',   'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8c2VhZm9vZCUyMGZpc2glMjBtYXJrZXQlMjBmcmVzaHxlbnwwfDB8fHwxNzg0NjE0OTUwfDA&ixlib=rb-4.1.0&w=1600&q=85&fm=jpg&fit=crop');
define('IK',  'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8ZnJlc2glMjByYXclMjBmaXNoJTIwaWNlJTIwbWFya2V0fGVufDB8MHx8fDE3ODQ2MTQ5NTF8MA&ixlib=rb-4.1.0&w=1600&q=85&fm=jpg&fit=crop');
define('PR',  'https://images.unsplash.com/photo-1576668919998-78ce5ffc3bd7?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8ZmlzaCUyMHdlaWdoaW5nJTIwc2NhbGUlMjB3b3JrZXJ8ZW58MHwwfHx8MTc4NDYxNDk1NHww&ixlib=rb-4.1.0&w=1600&q=85&fm=jpg&fit=crop');
define('CO',  'https://images.unsplash.com/photo-1498654200943-1088dd4438ae?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8Mnx8ZmlzaCUyMGljZSUyMGNvbGQlMjBzdG9yYWdlfGVufDB8MHx8fDE3ODQ2MTQ5NTZ8MA&ixlib=rb-4.1.0&w=1600&q=85&fm=jpg&fit=crop');
define('CU',  'https://images.unsplash.com/photo-1760047558843-e8c72b494c0d?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8ZnJlc2glMjBzcXVpZCUyMHJhdyUyMHNlYWZvb2R8ZW58MHwwfHx8MTc4NDYxNDk1N3ww&ixlib=rb-4.1.0&w=1600&q=85&fm=jpg&fit=crop');
define('MK',  'https://images.unsplash.com/photo-1597409244351-79ff2d5da5ee?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8ZmlzaCUyMG1hcmtldCUyMHZlbmRvcnxlbnwwfDB8fHwxNzg0NjE0OTU4fDA&ixlib=rb-4.1.0&w=1600&q=85&fm=jpg&fit=crop');
define('TA',  'https://images.unsplash.com/photo-1505441716189-50b06af1f43b?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8ZmlzaGVybWFuJTIwYm9hdCUyMGhhcmJvciUyMG1vcm5pbmd8ZW58MHwwfHx8MTc4NDYxNDk1OXww&ixlib=rb-4.1.0&w=1600&q=85&fm=jpg&fit=crop');
define('UD',  'https://images.unsplash.com/photo-1504309250229-4f08315f3b5c?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8ZnJlc2glMjBzaHJpbXAlMjBwcmF3biUyMHJhd3xlbnwwfDB8fHwxNzg0NjE0OTYwfDA&ixlib=rb-4.1.0&w=1600&q=85&fm=jpg&fit=crop');
define('CKP', 'https://images.unsplash.com/photo-1764345704514-7bf2934f360b?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8cmVkJTIwc25hcHBlciUyMGZpc2glMjBmcmVzaHxlbnwwfDF8fHwxNzg0NjE0OTYxfDA&ixlib=rb-4.1.0&w=600&h=750&q=85&fm=jpg&fit=crop');
define('CKR', 'https://images.unsplash.com/photo-1682045284951-d2dce9ff24a5?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8Z3JvdXBlciUyMGZpc2glMjBmcmVzaCUyMHdob2xlfGVufDB8MXx8fDE3ODQ2MTQ5NjJ8MA&ixlib=rb-4.1.0&w=600&h=750&q=85&fm=jpg&fit=crop');
define('CTN', 'https://images.unsplash.com/photo-1682457569891-53e4f6ef9271?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8ZnJlc2glMjB0dW5hJTIwZmlzaCUyMHdob2xlfGVufDB8MXx8fDE3ODQ2MTQ5NjN8MA&ixlib=rb-4.1.0&w=600&h=750&q=85&fm=jpg&fit=crop');
define('CTG', 'https://images.unsplash.com/photo-1735053671690-97833aac117a?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8bWFja2VyZWwlMjBmaXNoJTIwZnJlc2glMjByYXd8ZW58MHwxfHx8MTc4NDYxNDk2NHww&ixlib=rb-4.1.0&w=600&h=750&q=85&fm=jpg&fit=crop');
define('CBW', 'https://images.unsplash.com/photo-1706167754870-54c07a883197?ixid=M3wxMDAzMzMxfDB8MXxzZWFyY2h8MXx8c2lsdmVyJTIwZmlzaCUyMGZyZXNoJTIwd2hvbGUlMjByYXd8ZW58MHwxfHx8MTc4NDYxNDk2Nnww&ixlib=rb-4.1.0&w=600&h=750&q=85&fm=jpg&fit=crop');

$pdo = new PDO("mysql:host=localhost;dbname=db_wordpress;charset=utf8mb4","root","gggaming21");
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$ids = json_decode(file_get_contents(__DIR__.'/page_ids.json'), true);

function up($pdo,$pid,$k,$v){
    $r=$pdo->prepare("SELECT meta_id FROM wp_postmeta WHERE post_id=? AND meta_key=?");
    $r->execute([$pid,$k]);
    if($r->fetch()) $pdo->prepare("UPDATE wp_postmeta SET meta_value=? WHERE post_id=? AND meta_key=?")->execute([$v,$pid,$k]);
    else $pdo->prepare("INSERT INTO wp_postmeta(post_id,meta_key,meta_value)VALUES(?,?,?)")->execute([$pid,$k,$v]);
}
function sc($id,$bg,$cols){return['id'=>$id,'elType'=>'section','settings'=>['background_color'=>$bg,'padding'=>['unit'=>'px','top'=>'0','right'=>'0','bottom'=>'0','left'=>'0','isLinked'=>false]],'elements'=>$cols];}
function cl($id,$w,$ws){return['id'=>$id,'elType'=>'column','settings'=>['_column_size'=>$w],'elements'=>$ws];}
function ht($id,$h){return['id'=>$id,'elType'=>'widget','widgetType'=>'text-editor','settings'=>['editor'=>$h]];}

echo "\n=== 08-inject-fixed.php running... ===\n";

require __DIR__ . '/08-inject-body.php';
